
package com.maquendi.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "myFirsWS", targetNamespace = "http://webServices.maquendi.com/", wsdlLocation = "http://localhost:9999/wsApp/myFirsWS?WSDL")
public class MyFirsWS_Service
    extends Service
{

    private final static URL MYFIRSWS_WSDL_LOCATION;
    private final static WebServiceException MYFIRSWS_EXCEPTION;
    private final static QName MYFIRSWS_QNAME = new QName("http://webServices.maquendi.com/", "myFirsWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/wsApp/myFirsWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYFIRSWS_WSDL_LOCATION = url;
        MYFIRSWS_EXCEPTION = e;
    }

    public MyFirsWS_Service() {
        super(__getWsdlLocation(), MYFIRSWS_QNAME);
    }

    public MyFirsWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYFIRSWS_QNAME, features);
    }

    public MyFirsWS_Service(URL wsdlLocation) {
        super(wsdlLocation, MYFIRSWS_QNAME);
    }

    public MyFirsWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYFIRSWS_QNAME, features);
    }

    public MyFirsWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyFirsWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyFirsWS
     */
    @WebEndpoint(name = "myFirsWSPort")
    public MyFirsWS getMyFirsWSPort() {
        return super.getPort(new QName("http://webServices.maquendi.com/", "myFirsWSPort"), MyFirsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyFirsWS
     */
    @WebEndpoint(name = "myFirsWSPort")
    public MyFirsWS getMyFirsWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.maquendi.com/", "myFirsWSPort"), MyFirsWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYFIRSWS_EXCEPTION!= null) {
            throw MYFIRSWS_EXCEPTION;
        }
        return MYFIRSWS_WSDL_LOCATION;
    }

}
