
package com.maquendi.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "myFirsWS", targetNamespace = "http://webServices.maquendi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyFirsWS {


    /**
     * 
     * @param nac
     * @param tipo
     * @param pass
     * @param apellido
     * @param sexo
     * @param userName
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Register")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Register", targetNamespace = "http://webServices.maquendi.com/", className = "com.maquendi.webservices.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://webServices.maquendi.com/", className = "com.maquendi.webservices.RegisterResponse")
    @Action(input = "http://webServices.maquendi.com/myFirsWS/RegisterRequest", output = "http://webServices.maquendi.com/myFirsWS/RegisterResponse")
    public String register(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "apellido", targetNamespace = "")
        String apellido,
        @WebParam(name = "nac", targetNamespace = "")
        XMLGregorianCalendar nac,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.maquendi.webservices.User
     */
    @WebMethod(operationName = "validate_user")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validate_user", targetNamespace = "http://webServices.maquendi.com/", className = "com.maquendi.webservices.ValidateUser")
    @ResponseWrapper(localName = "validate_userResponse", targetNamespace = "http://webServices.maquendi.com/", className = "com.maquendi.webservices.ValidateUserResponse")
    @Action(input = "http://webServices.maquendi.com/myFirsWS/validate_userRequest", output = "http://webServices.maquendi.com/myFirsWS/validate_userResponse")
    public User validateUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Registrar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Registrar", targetNamespace = "http://webServices.maquendi.com/", className = "com.maquendi.webservices.Registrar")
    @ResponseWrapper(localName = "RegistrarResponse", targetNamespace = "http://webServices.maquendi.com/", className = "com.maquendi.webservices.RegistrarResponse")
    @Action(input = "http://webServices.maquendi.com/myFirsWS/RegistrarRequest", output = "http://webServices.maquendi.com/myFirsWS/RegistrarResponse")
    public String registrar(
        @WebParam(name = "user", targetNamespace = "")
        User user);

}
